### ISSUE TITLE
Do IE and Miscrosoft Edge officially not support Webgl 1.0?

### ISSUE THREAD

**Issue by yshbatra** [KhronosGroup/WebGL#1181]
Hi guys,

I can see that many conformace tests failures are there on IE and Edge browser. But these browsers do support Webgl 1.0. Do we have any reasons why these browsers are not whitelisted for webgl support by Khronos?

**Comment by toji** [comment]
Depending on the version of the conformance tests that you are running, Chrome, Firefox, and Safari all encounter failures as well. The latest version of the test (1.0.4) has known failures everywhere, but if you go back to the [1.0.1](https://www.khronos.org/registry/webgl/conformance-suites/1.0.1/webgl-conformance-tests.html) or [1.0.2](https://www.khronos.org/registry/webgl/conformance-suites/1.0.2/webgl-conformance-tests.html) snapshots some browsers can pass 100%. To be considered a conformant WebGL implementation a browser has to at least pass the 1.0.1 tests.

Microsoft's browsers, IIRC, do have a few know issues with 1.0.1 conformance. The failures are in less common behavior, and IE/Edge will render most WebGL correctly, but technically they can't be considered conformant just yet. As a result I believe they still expose their WebGL context as "experimental-webgl" instead of just "webgl".

Khronos doesn't need to whitelist any browsers, they just have to fix the remaining bugs so that they pass the tests.
