### ISSUE TITLE
RFE: GL_EXT_sRGB_write_control

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#1332]
We've received feedback from a customer that the GL_EXT_sRGB_write_control extension is important for them to enable their linear rendering path. This is easily implementable on top of desktop OpenGL. A sampling of a couple of Android devices indicates it's probably reasonably well supported. It doesn't appear to be supported on iOS.

**Comment by Groovounet** [comment]
Hi,

How use case is to "keep using code that is confused about some of its color specifications". However, a legitimate use case is to share memory to render in both sRGB and linear mode.

It looks like we will deprecate the code requiring that feature within 6 to 12 months because we have the same issue with Android and iOS devices anyway. We will still use that code (to render the editor UI) but I expect that nobody will fix that code ever.

If you want to drop this feature, I think it's fine.

Thanks,
Christophe

**Comment by kenrussell** [comment]
Thanks Christophe for your response on this. Other feedback has been received that this feature was deliberately dropped in OpenGL ES, and that the strong preference is to preserve OpenGL ES's semantics in WebGL. With your response, I'll close this RFE.
