### ISSUE TITLE
Clarify uniform block layout rules

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#1534]
Gregg Tavares pointed out on the public_webgl list that the default packing for uniform blocks is "packed" in ES 3.0, but WebGL's only supported layout is "std140". A decision needs to be made about how shaders not specifying the layout will be handled. One suggestion is to forbid compilation of shaders using uniform blocks which have no layout specifier. Another is to auto-upgrade these uniform blocks' layouts to std140 in WebGL.

https://www.khronos.org/webgl/public-mailing-list/archives/1603/msg00000.php

**Comment by greggman** [comment]
Actually the default is `shared` (opengl es glsl 3.0 section 4.3.8.3) but in any case it's not `std140`.

My suggestion was rather than the forbid `shared` and `packed` just define the layouts of `shared` and `packed` as `std140` for WebGL so from the POV of apps using WebGL they can just use any shader they were already using from actual OpenGL ES 3.0. This should work because if they were using either `shared` or `packed`, those are implementation dependent layouts which means their code should already be looking up the offsets

For WebGL implementations to enforce that `packed` and `shared` layouts are `std140` all it seems they have to do is re-write the shaders, first inserting `layout(std140) uniform;` at the top of the shader (which they probably do now) and then replacing `packed` and `shared` with `std140` throughout the user's shader. 

Do this seems like it would make porting much easier

**Comment by greggman** [comment]
I guess I don't understand how it would cause problems. I'm not an expert on ES 3 but my understanding is

`packed` = machine dependent format, possibly removing unused fields

`shared` = machine dependent format, don't remove unused fields as they might be used in some other shader.

`std140` = machine independent format defined in spec.

From the POV of any app `packed` and `shared` have to be queried since it's machine dependant. In fact it could change with each version of the driver. 

You can consider WebGL a virtual driver that just happens to define the formats for `packed` and `shared`. The app itself doesn't care what the layout is with `packed` and `shared` it only cares that if they specify `std140` they get the standard layout.

**Comment by greggman** [comment]
I guess maybe you're saying there could be a problem for people that start on WebGL 2 and the port to OpenGL ES 3.0 because they might expect packed and shared to have the same format they had on WebGL 2?  That's true but they'd have the same issue regardless of if they started in WebGL 2 or OpenGL ES 3 if they assumed a certain format for packed or shared.

**Comment by kenrussell** [comment]
My concern is more that there may be some important difference in layout or behavior between packed/shared and std140 in pure ES 3.0. Having WebGL treat all of them the same may confuse developers who assume their shaders will behave identically between ES 3.0 and WebGL 2.0.

An analogue is that WebGL 1.0, like ES 2.0, declares there is no default floating-point precision qualifier in fragment shaders. This would have been easy to declare as "mediump", but it was better to be more explicit so developers knew what was going on under the hood.

I don't have a strong opinion on this particular issue, but it definitely needs to be resolved one way or the other.

**Comment by greggman** [comment]
What ever happened here? 

if `shared` and `packed` don't become synonyms for `std140` in WebGL 2 then any projects being ported to WebGL2 are going to require all of their shaders to be re-written.

**Comment by kenrussell** [comment]
Sorry, I dropped this on the floor. @jdashg since Firefox is the other WebGL 2.0 implementation close to shipping, do you have an opinion on this?

It'd be straightforward to alias `shared` and `packed` to `std140` in ANGLE's shader translator. We've talked with OpenGL ES implementers in the past who have indicated that there should be no performance penalty from using std140 as the standard layout for WebGL.

@grorg @RafaelCintron @zhenyao please give this some thought as well. I suppose rather than being overly strict about this, WebGL 2.0 should be more lenient, to minimize porting issues.

**Comment by kenrussell** [comment]
There hasn't been any comment from other implementers on this so I've moved ahead and filed:

https://bugs.chromium.org/p/angleproject/issues/detail?id=1542

to track adding this support to ANGLE's shader translator, and:

https://bugs.chromium.org/p/chromium/issues/detail?id=654597

to track turning it on in Chromium and adding conformance tests.

It should be trivial for Firefox to pick up this fix, just by enabling another compiler option when instantiating ANGLE's shader translator.

**Comment by zhenyao** [comment]
Per today's working group discussion, the consensus is to only allow std140 and that should be the default (will need a spec update). The reason is that we don't want to mislead people to believe that packed or shared are portable in native ES3 apps (and they would be in WebGL2 if we allow them).
