### ISSUE TITLE
No tests for no attribute shaders in WebGL 1.0 (and 2.0?) conformance tests

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#1954]
I made a shader like this

    void main() {
      gl_PointSize = 100.0;
      gl_Position = vec4(0, 0, 0, 1);
    }

Then with no buffers and no attributes I called `gl.drawArrays(gl.POINTS, 0, 1)`.

This works in Firefox and Chrome but fails in Safari. It probably needs a test?

Interestingly Safari succeeds if I add an attribute but don't actually set one up. In other words

    attribute vec4 position;
    void main() {
      gl_PointSize = 100.0;
      gl_Position = position;
    }

But I don't create any buffers nor do I enable any attributes

Note [vertexshaderart.com](http://vertexshaderart.com) is entirely based on no attribute shaders. You can think of it as

    void main() {
      // use gl_VertexId to generate values for gl_Position
      ...
    }

    ...
    gl.drawArrays(mode, 0, count);

No attributes. 

Currently vertexshaderart.com is using an attribute to supply the vertex id because it's WebGL 1.0 which doesn't support `gl_VertexId` but WebGL 2.0 does and so it should function with no attributes.

Here's a live example: https://jsfiddle.net/greggman/0qtcc2v0/

Safari gets 

    [Warning] WebGL: INVALID_OPERATION: drawArrays: attempt to access out of bounds arrays

**Comment by kenrussell** [comment]
Thanks for reporting this. I'm embarrassed to say I found out about the problems with no-attribute programs a few years ago when the WebGL Programming Guide was written, but it seemed like such a corner case that I didn't file a bug or write a conformance test for it.

Agree that in WebGL 2.0 this is a much more important case to make work. Do you think you could provide a conformance test for this, perhaps under sdk/tests/conformance2/glsl3/ ? Or at least a suggestion on how this test should be written? Could be a little tricky since the only browsers with WebGL 2.0 implementations right now are Firefox and Chrome.

A WebGL 1.0 conformance test would be welcome, too, but I'd like to defer making all the browsers work around this bug in WebGL 1.0 until WebGL 2.0 is out the door -- which shouldn't take long now.

**Comment by zhenyao** [comment]
Should we close this since we do have a conformance test for this (Thanks Gregg to locate it)?

**Comment by kenrussell** [comment]
@zhenyao good point, and @greggman , thanks for finding the test as well as writing your new one in #1957 . I think it is worth adding the new WebGL 2.0 test, and merged that pull request, so let's close this. Thanks again for helping expand the tests.
