### ISSUE TITLE
Invalid Enum/Value errors on some functions with Webgl 2.0

### ISSUE THREAD

**Issue by pixelnerve** [KhronosGroup/WebGL#1963]
Catching errors on the following lines:

returns GL_INVALID_ENUM on:
- glGetProgramiv( handle, GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH, &maxNameLen );
- glGetIntegerv( GL_VERTEX_ARRAY_BINDING, &prevVao );

returns GL_INVALID_VALUE on:
- glGetActiveUniformBlockiv( handle, uniformBlockIndex, GL_UNIFORM_BLOCK_BINDING, &cbBlockBindingPoint );

**Comment by kenrussell** [comment]
WebGL 2.0 doesn't expose the GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH enum because getActiveUniformBlockName in WebGL returns a DOMString which implicitly contains the length.

glGetIntegerv(GL_VERTEX_ARRAY_BINDING, &prevVao) becomes:
gl.getParameter(gl.VERTEX_ARRAY_BINDING)

glGetActiveUniformBlockiv(handle, uniformBlockIndex, GL_UNIFORM_BLOCK_BINDING, &cbBlockBindingPoint) becomes:
gl.getActiveUniformBlockParameter(program, uniformBlockIndex, gl.UNIFORM_BLOCK_BINDING)

I'm not sure which environment in which you're porting code but if it's Emscripten (for example) there are probably bugs in their bindings between OpenGL ES 3.0 and WebGL 2.0.

Otherwise, please provide a small, self-contained test case demonstrating the errors, and we'll fix them and add your test to the conformance suite.

**Comment by pixelnerve** [comment]
This was used with Emscripten and has been fixed since then

**Comment by kenrussell** [comment]
Thanks for following up. Closing this issue as it wasn't a bug in the WebGL spec or implementation.

**Comment by larsbohn** [comment]
I just stumbled upon this issue in the current ( 46afd23 ) version of emscripten.

glGetIntegerv(GL_VERTEX_ARRAY_BINDING, &aGLInt);

gives  INVALID_ENUM in WebGL 1.0 contexts with OES_vertex_array_object present and activated.

This seems to be because in

https://github.com/kripken/emscripten/blob/incoming/src/library_gl.js

#if USE_WEBGL2
              case 0x85B5: // GL_VERTEX_ARRAY_BINDING
              case 0x8919: // GL_SAMPLER_BINDING
              case 0x8E25: // GL_TRANSFORM_FEEDBACK_BINDING
#endif

--> only if WebGL2 is used the call is actually executed, but not if just the extension is present...
