### ISSUE TITLE
Should trying to bind a deleted renderbuffer clear the current binding or silently ignore it?

### ISSUE THREAD

**Issue by emilio** [KhronosGroup/WebGL#1991]
At Servo we've had this discussion in https://github.com/servo/servo/pull/12934, so we looked what other engines do, and found conflicting implementations.

On one hand, Gecko silently ignores them: http://searchfox.org/mozilla-central/source/dom/canvas/WebGLContextGL.cpp#173

On the other hand, Chromium sets the buffer pointer to null, clearing the binding: https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/webgl/WebGLRenderingContextBase.cpp?sq=package:chromium&rcl=1472224659&l=1551

What should be the adequate behavior? The current spec only specifies that is null is given, the binding should be cleared, but it leaves this case unspecified.

**Comment by kenrussell** [comment]
Very good question.

I would have hoped that one of the WebGL conformance tests would have covered this -- perhaps sdk/tests/conformance/misc/object-deletion-behaviour.html . Unfortunately, given Firefox's and Chrome's differing behavior, it seems clear this isn't tested.

Chrome treats all incoming deleted objects to bind calls, not just renderbuffers, as though 0 were being bound to the target.

It's difficult to argue for one behavior or the other. At the native API level, deleted objects can be kept alive by objects that reference them. See appendix C.1.3 of the ES 2.0.25 specification. In general, since binding an unused name in OpenGL ES creates a new object, doing this at the native API level usually creates a new object of the same name -- behavior that is not compatible with the way WebGL works, since it requires calling the create* methods to create new objects.

I somewhat like Chrome's current behavior since clearing the current binding will probably make it more obvious to the programmer that they have made an error, rather than silently leaving the binding in its previous state. Regardless, the behavior must be defined and a test written.

Comments @zhenyao @jdashg @grorg @RafaelCintron ?

**Comment by zhenyao** [comment]
Or another option is to generate an INVALID_OP, making it clear it's not a valid op.

**Comment by emilio** [comment]
Heh, indeed, blaming Gecko's implementation it seems they originally generated an INVALID_OP, but removed that to pass conformance tests: https://bugzilla.mozilla.org/show_bug.cgi?id=681835#c1

**Comment by kenrussell** [comment]
Argh.

I don't remember why this behavior was chosen instead of being more strict and generating an error. Is there some use case where it's desirable to silently accept deleted objects? As an example, all of the uniform* API calls accept a null WebGLUniform object, because that's the way the native API works.

Have you tried generating an invalid operation error and also asserting, running some random content on the web, and seeing if the assertion is hit? That would help clarify the impact to real-world content.

**Comment by emilio** [comment]
Just ran for half an hour or so through some WebGL-heavy sites with a debug version of Gecko with this patch:

```diff
diff --git a/dom/canvas/WebGLContextGL.cpp b/dom/canvas/WebGLContextGL.cpp
index 44c696e..a02c4ed 100644
--- a/dom/canvas/WebGLContextGL.cpp
+++ b/dom/canvas/WebGLContextGL.cpp
@@ -126,9 +126,7 @@ WebGLContext::BindFramebuffer(GLenum target, WebGLFramebuffer* wfb)
     if (!ValidateObjectAllowDeletedOrNull("bindFramebuffer", wfb))
         return;
 
-    // silently ignore a deleted frame buffer
-    if (wfb && wfb->IsDeleted())
-        return;
+    MOZ_ASSERT(!wfb || !wfb->IsDeleted());
 
     MakeContextCurrent();
 
@@ -170,9 +168,7 @@ WebGLContext::BindRenderbuffer(GLenum target, WebGLRenderbuffer* wrb)
     if (!ValidateObjectAllowDeletedOrNull("bindRenderbuffer", wrb))
         return;
 
-    // silently ignore a deleted buffer
-    if (wrb && wrb->IsDeleted())
-        return;
+    MOZ_ASSERT(!wrb || !wrb->IsDeleted());
 
     // Usually, we would now call into glBindRenderbuffer. However, since we have to
     // potentially emulate packed-depth-stencil, there's not a specific renderbuffer that
```

And no assertion hit.

**Comment by RafaelCintron** [comment]
FWIW, Edge currently follows Chrome's behavior: clear the binding without flagging an error.  Flagging an error seems like a good "You're Doing it Wrong" hint to the web developer.  If flagging an error does not break content, I could get behind that as a solution.

**Comment by kenrussell** [comment]
Thanks @emilio for testing and @RafaelCintron for your input. I agree that it would be better to unify the behavior among browsers and to be more strict. This is an area where the underlying API can't really be, since there are no "wrappers" for the names that are generated.

@emilio do you think you could see how large a change to the WebGL conformance suite it would be to change the behavior in this area? i.e., change Firefox to generate INVALID_OPERATION, see which tests fail, and put together a pull request?

**Comment by emilio** [comment]
@kenrussell: Sure, I can't promise it will be right now, but I can try to take some time this week to do that.

**Comment by kenrussell** [comment]
@emilio : of course. No huge rush. The Firefox and Chrome teams are in the throes of trying to ship WebGL 2.0 so honestly nobody would be sad if this somewhat large change were delayed a few weeks. :)

**Comment by emilio** [comment]
Try run and patch here: https://treeherder.mozilla.org/#/jobs?repo=try&revision=a202376ccda2

Seems like only object-deletion-behaviour.html needs to change?

**Comment by kenrussell** [comment]
That'd be a relief if that's the only test that needs to be updated.

Please double-check any test failure suppressions that Firefox may have in place, but other than that it sounds like this change is fine to make.

Note that we should also update the specification this time!

**Comment by emilio** [comment]
This is pretty much solved, thanks all! :-)

**Comment by zhenyao** [comment]
Note there are some webgl2 tests being affected:

See https://github.com/KhronosGroup/WebGL/pull/2018
