### ISSUE TITLE
IDL for WebGL2RenderingContext is not valid: has multiple identical overloads of bufferData

### ISSUE THREAD

**Issue by bzbarsky** [KhronosGroup/WebGL#2216]
The relevant bits are, from https://www.khronos.org/registry/webgl/specs/latest/2.0/webgl2.idl and https://www.khronos.org/registry/webgl/specs/latest/1.0/webgl.idl :

    [NoInterfaceObject]
    interface WebGL2RenderingContextBase
    {
    ...
      // WebGL1:
      void bufferData(GLenum target, GLsizeiptr size, GLenum usage);
      void bufferData(GLenum target, ArrayBuffer? srcData, GLenum usage);
      void bufferData(GLenum target, ArrayBufferView srcData, GLenum usage);
    ...
      // WebGL2:
      void bufferData(GLenum target, ArrayBufferView srcData, GLenum usage, GLuint srcOffset,
                      optional GLuint length = 0);
    ...
    };

    WebGL2RenderingContextBase implements WebGLRenderingContextBase;

    [NoInterfaceObject]
    interface WebGLRenderingContextBase
    {
      void bufferData(GLenum target, GLsizeiptr size, GLenum usage);
      void bufferData(GLenum target, ArrayBuffer? data, GLenum usage);
      void bufferData(GLenum target, ArrayBufferView data, GLenum usage);
    };

The "webgl1" versions of bufferData are present twice: once directly and once pulled in via the `implements` statement.  That leads to there being identical overloads, which is not valid IDL.

There are similar problems, at first glance, with bufferSubData, texImage2D, etc.

**Comment by kenrussell** [comment]
We studied this when adding these overloads. https://heycam.github.io/webidl/#idl-overloading seems to indicate that only the current interface, and not all of its inherited interfaces per https://heycam.github.io/webidl/#idl-interfaces , are considered when computing the effective overload set. This is why the WebGL 1.0 entry points were duplicated in the WebGL2RenderingContextBase.

@jdashg what did you find when pulling this IDL into Firefox? Or is this bug a result of attempting to do so?

Happy to remove these if they're not valid. I don't think we attempted to pull this IDL into Chrome verbatim; rather, we selectively added the new overloads, and it's possible that our IDL parser would reject adding the WebGL 1.0 overloads.

**Comment by bzbarsky** [comment]
> and not all of its inherited interfaces

There are no inherited interfaces here.  Just stuff being pulled in via "implements", right?

> @jdashg what did you find when pulling this IDL into Firefox?

This IDL hasn't been put into Firefox.  In Firefox, WebGL2RenderingContext inherits from WebGLRenderinContext, and _then_ it needs these copied-over things because otherwise the behavior is wrong.

I should also note that adding overloads via mixins (read "implements" statement) is not a great pattern in general and I'm not sure IDL should support it.  See <https://github.com/heycam/webidl/issues/261>.  But the concern there applies to mixing into an existing interface; maybe mixing into a mixin is ok.  It's hard to tell; either way you have two independent definitions of what the method should do that can interact in undesirable ways and have to be coordinated very carefully.  At which point having them be technically in different specs or on different interfaces is more or less a fiction: it's all one spec.

**Comment by kenrussell** [comment]
WebGL2RenderingContext is not supposed to inherit directly from WebGLRenderingContext. The intent was this behavior (copied from Chromium's DevTools console):

&gt; c = document.createElement('canvas')
&lt; _&lt;canvas&gt;​_
&gt; gl = c.getContext('webgl2')
&lt; _WebGL2RenderingContext {canvas: canvas, drawingBufferWidth: 300, drawingBufferHeight: 150}_
&gt; gl instanceof WebGL2RenderingContext
&lt; _true_
&gt; gl instanceof WebGLRenderingContext
&lt; _false_

Shame on me for not enforcing this in sdk/tests/conformance2/context/context-type-test-2.html . If this change is made will it cause problems for Firefox?

Should we change the various interfaces in the WebGL specs to use inheritance instead of the "implements" keyword? To be honest I thought this was the case at one point, but can't find evidence of it in the version history.

**Comment by bzbarsky** [comment]
> WebGL2RenderingContext is not supposed to inherit directly from WebGLRenderingContext. 

Yes, I'm aware.  That's why I filed <https://bugzilla.mozilla.org/show_bug.cgi?id=1324543>.

> If this change is made will it cause problems for Firefox?

That's a question for @jdashg.  Note that our WebGL2 implementation is behind a flag so far.

> Should we change the various interfaces in the WebGL specs to use inheritance instead of the "implements" keyword?

That depends on the behavior you're trying to produce.  Note that inheritance would still require explicitly listing the "webgl1" versions of the overload (as Gecko's IDL and the spec do now) because two different "overloads" that are not on the same interface in the end are not actually overloads of each other; one is just shadowing the other.

**Comment by jdashg** [comment]
@bzbarsky It is currently behind a flag on Release, but not Beta or newer, as it is shipping in Firefox in 51.

@kenrussell Will enforcing this cause problems for Firefox? Likely yes. We can fix this in 52+, but likely not 51 without a bunch of DOM bindings glue changes.

Let's punt this to 2.0.1.

**Comment by kenrussell** [comment]
@bzbarsky The main goal is for WebGLRenderingContext and WebGL2RenderingContext to not be related via inheritance, while still using inheritance or mixins to make WebGL 2.0 largely a superset of WebGL 1.0. It sounds like either using "implements" and removing the copy of the WebGL 1.0 entry points from WebGL2RenderingContextBase, or switching to using inheritance, would work. Is that correct? I would lean more toward continuing to use "implements" to describe the behavior simply because it's a smaller change and I don't know whether Chrome's Web IDL parser will handle using inheritance.

@jdashg Don't worry, there was no intention of changing the 2.0.0 conformance snapshot, only the top-of-tree tests (which are already 2.0.1 beta).

**Comment by bzbarsky** [comment]
> It sounds like either using "implements" and removing the copy of the WebGL 1.0 entry points from WebGL2RenderingContextBase, or switching to using inheritance, would work. Is that correct? 

I'm not sure what you mean by "switching to using inheritance" here...

**Comment by bzbarsky** [comment]
Some other duplicated things: DEPTH_STENCIL, DEPTH_STENCIL_ATTACHMENT.

uniform*fv/iv and uniformMatrix*fv have indistinguishable overloads.  For example, webgl1 has:

    void uniform1fv(WebGLUniformLocation? location, Float32Array v);
    void uniform1fv(WebGLUniformLocation? location, sequence<GLfloat> v);

and webgl2 has:

    void uniform1fv(WebGLUniformLocation? location, Float32List data, optional GLuint srcOffset = 0,
                  optional GLuint srcLength = 0);

Should a call with two arguments invoke one of the webgl1 overloads, or the webgl2 one?  You can't tell, so IDL doesn't allow this.

**Comment by nox** [comment]
The [spec](https://heycam.github.io/webidl/#idl-overloading) says:

> Operations must not be overloaded across interface, partial interface, interface mixin, and partial interface mixin definitions.

So AFAIK the `bufferData` overloads etc are wrong.

**Comment by bzbarsky** [comment]
> The spec says:

That came from a spec change after this IDL was written.  See history of this issue.

**Comment by kenrussell** [comment]
Sorry for letting this sit so long.

The WebGL IDL files can be updated, but it would be ideal if there were some WebIDL validator that would both catch the current errors, and confirm that making these changes would address them.

https://www.w3.org/2009/07/webidl-check doesn't parse the WebGL 1.0 spec successfully due to the use of the [AllowShared] extended IDL attribute. It's not clear to me whether https://github.com/dontcallmedom/widlproc itself is up to date with the current spec; I didn't try compiling it.

https://github.com/w3c/webidl2.js seemed more up to date, judging by the date of recent commits. I uploaded https://github.com/w3c/webidl2.js/pull/145 fixing a bug and https://github.com/w3c/webidl2.js/pull/146 adding a simple online WebIDL checker. Unfortunately, this one successfully parses the concatenated WebGL 1.0 and 2.0 IDL files without reporting any errors.

Do you have any suggestions for how to verify these proposed changes to WebGL's IDL?

**Comment by saschanaz** [comment]
So the faulty operations are:

* `bufferData`
* `bufferSubData`
* `texImage2D`
* `texSubImage2D`
* `compressedTexImage2D`
* `uniform1fv`
* `uniform2fv`
* `uniform3fv`
* `uniform4fv`
* `uniform1iv`
* `uniform2iv`
* `uniform3iv`
* `uniform4iv`
* `uniformMatrix2fv`
* `uniformMatrix3fv`
* `uniformMatrix4fv`
* `readPixels`

How about doing this way?

```webidl
interface mixin WebGLRenderingContextOverloads {
  void bufferData(GLenum target, GLsizeiptr size, GLenum usage);
  void bufferData(GLenum target, [AllowShared] BufferSource? srcData, GLenum usage);
  void bufferSubData(GLenum target, GLintptr dstByteOffset, [AllowShared] BufferSource srcData);
  // ... other WebGL 1 versions of overloads ...
};

WebGLRenderingContext includes WebGLRenderingContextBase;
WebGLRenderingContext includes WebGLRenderingContextOverloads;

interface mixin WebGL2RenderingContextOverloads {
  // WebGL1:
  void bufferData(GLenum target, GLsizeiptr size, GLenum usage);
  void bufferData(GLenum target, [AllowShared] BufferSource? srcData, GLenum usage);
  void bufferSubData(GLenum target, GLintptr dstByteOffset, [AllowShared] BufferSource srcData);
  // WebGL2:
  void bufferData(GLenum target, [AllowShared] ArrayBufferView srcData, GLenum usage, GLuint srcOffset,
                  optional GLuint length = 0);
  // ... other WebGL 1 versions of overloads ...
  // ... other WebGL 2 versions of overloads ...
};

WebGL2RenderingContext includes WebGLRenderingContextBase;
WebGL2RenderingContext includes WebGL2RenderingContextBase;
WebGL2RenderingContext includes WebGL2RenderingContextOverloads;
```

**Comment by bzbarsky** [comment]
> Do you have any suggestions for how to verify these proposed changes to WebGL's IDL?

Sorry for the lag in responding to this.

At the moment, the best option is to try applying them to all of WebKit, Chromium, and Gecko and building and seeing whether any of the binding generators complain.

Ideally either respec or idlharness or both would do validation, but they are not very good at it so far.

That said, I'm not sure it would help in this case.  https://github.com/web-platform-tests/wpt/blob/77525b8ae8a8b194c62168029c78f57d54d012e7/interfaces/webgl1.idl#L540 and https://github.com/web-platform-tests/wpt/blob/77525b8ae8a8b194c62168029c78f57d54d012e7/interfaces/webgl2.idl#L304 both exist but there is no test that actually uses them, so they never get validated.  That should probably be fixed.  I don't know whether webgl2 uses respec.
