### ISSUE TITLE
powerPreference is overly strict

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2343]
The powerPreference attribute says it only works if listeners exist for 'weblcontextlost` and `webglcontextrestored`

This makes no sense. Multiple GPUs are already a part of many windows machines with multiple GPU cards and multiple monitors. Turning off a single GPU or even updating drivers without rebooting (drivers that might enable or disable features) has been a part of Windows since Windows Vista.

Adding to OSX to the list of systems that might switch GPUs (given that `powerPreference` feature was added by Apple) doesn't add any new issues to WebGL and this feature should arguably not be so convoluted.

99.999% of all WebGL app do not support contextlost and are unlikely to anytime soon. That means most people (and probably three.js) are just probably going to no-op the listeners since they likely want to default to `high-performance` and therefore no problems will have been solved

     canvas.addEventListener('webglcontextlost`, function() {});
     canvas.addEventListener('webglcontextrestored`, function() {});
     let gl = canvas.getContext("webgl", { powerPreference: "high-performance" });

It seems like the listener requirements should be removed

**Comment by ivanpopelyshev** [comment]
Some widely-used renderer libraries (pixi.js) support context loss, so I don't think its 99,99% ;)

**Comment by toji** [comment]
I sympathize with what @greggman is saying, but I'd actually argue that we should be advocating for more libraries to support context loss rather than avoid ever introducing dependencies on that behavior. (We should avoid context loss whenever possible too, but that doesn't negate the need for apps to handle it.)

On the WebVR side we're planning on introducing a similar dependency to ensure that contexts are on the correct adapter for a VR HMD. As part of that effort we're petitioning Three.js to add better context loss support: https://github.com/mrdoob/three.js/issues/11435

**Comment by ivanpopelyshev** [comment]
Btw, https://github.com/EsotericSoftware/spine-runtimes/tree/3.6/spine-ts supports context loss too,

**Comment by jpweeks** [comment]
I'd also like to point out that some apps do support context loss, but don't add the listeners until after context creation. I've recently realized this seems to be the issue with `powerPreference` in an app I'm building that uses [regl](https://github.com/regl-project/regl). Although the library can be patched to work around this behavior, it feels like not obvious behavior, especially since requesting `'high-performance'` without the listeners fails silently.

**Comment by zhenyao** [comment]
Then what happens if GPU switching happens between context creation and adding a listener to context lost? It will cause more trouble for developers if behaviors becomes racy.

**Comment by jdashg** [comment]
Fixing this in #2939.
