### ISSUE TITLE
WebGL2 Buffer restrictions overly restrictive?

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#2346]
[The WebGL2 spec, section 5.1 says](https://www.khronos.org/registry/webgl/specs/latest/2.0/#5.1)

> In addition, a buffer can not be simultaneously bound to a transform feedback buffer binding point and another buffer binding point in the WebGL 2 API. Attempting to violate this rule generates an INVALID_OPERATION error, and the state of the binding point will remain untouched.

I agree with the need for the restriction but the actual enforcement seems not  really in the spirit of OpenGL. It seems like this would be checked at draw time not bind time.

Just like it's okay to do this

1. Upload RGB to level 1 of a texture
2. Upload RGBA to level 0 of a texture 
3. Call gl.generateMips

Level 1 will be overwritten. No error was issued on step 2 that the mips didn't match format.

Another example.

1. make framebuffer
2. make texture
3. attach texture
4. call texImage2d to set format of texture

Some implementations would consider issuing an error at step 3 because the texture is not yet renderable but that's not the OpenGL way. The checks don't happen until draw time.

Maybe a better example

1. make and bind framebuffer
2. make and bind texture
3. attach texture to framebuffer
4. unbind texture

If I was to render at step 3 I'd get an error because the texture is both an input and and output. I don't get an error though because it's not checked until draw time. If restriction similar to the buffer restriction was added step 4 would have to come before step 3.

It seems like these buffer binding restrictions should work the same texture binding restrictions and other similar things, checked for at draw time. In fact I'd suspect checking and bind time will break lots of ported content that expects to be able to have things temporarily bound to multiple bind points and work like it does for textures.

Unless I'm mis-understanding how transformfeedback state works it seems like the spec should say along the lines of 

> In addition, when calling any drawing function a buffer can not be simultaneously bound to a transform feedback buffer binding point and attached to an attribute in the currently bound vertexarrayobject or a global attribute if no vertexarrayobject is bound. Attempting to violate this rule generates an INVALID_OPERATION error.

**Comment by greggman** [comment]
Here's a test showing Chrome is broken in this area

https://jsfiddle.net/greggman/vp1p7973/

Firefox passes the test

It's related to the way Chrome is (or was) handling transform feedback.

You can see how in the test, checking at `gl.bindBuffer` time is NOT a useful test. The test has to happen at draw time. The test shows Firefox catches the error and Chrome does not.

It seems like the spec above needs to change. Remove the binding restrictions and add the draw time check requirements.

**Comment by kenrussell** [comment]
This came up in the working group some time ago. @zhenyao pointed out that checks would need to be added to all of the API calls which can read from or write to buffers:
tex{Sub}Image{2|3}D
compressedTex{Sub}Image{2|3}D
readPixels
draw{Instanced}Arrays
draw{Instanced}Elements
drawRangeElements
buffer{Sub}Data
copyBufferSubData
getBufferSubData
(mapBufferRange, unmapBufferRange) - don't exist in WebGL

@jdashg from Mozilla stated that it's feasible to do these checks relatively cheaply at these points. I gave this some thought and see how it can be done in the way he pointed out -- by keeping track of the number of non-TF binding points each Buffer is attached to, and only checking the currently bound TF object for conflicts.

I'll take on the task of updating the spec and conformance tests in this area.

**Comment by greggman** [comment]
I just wanted to double check but when you say *all these API calls* I assume each call only needs to check certain things. For example `copyBufferSubData` only needs to check that the 2 buffers involved in the copy are not the same buffer. It does not need to check that all other buffer bind points are not using those buffers which is suggested by the current gl.bindBuffer spec.

`drawXXX` only needs to check that the buffers referenced by the current vertex array don't conflict with the buffers referenced by the current transform feedback assuming that transform feedback is enabled. draws do not need to check unrelated buffer bind points.

etc...

**Comment by zhenyao** [comment]
If we check at use time instead of bind time, then yes, we should only check the related binding points, not all binding points.

for drawXXX though, it's more than the current vertex array buffers.  It's also uniform buffers from transform feedback buffers.

**Comment by zhenyao** [comment]
OpenGL ES 3.0.4  Section 2.15.2, Transform Feedback Primitive Capture:
"Buffers should not be bound or in use for both transform feedback and other
purposes in the GL. Specifically, if a buffer object is simultaneously bound to a
transform feedback buffer binding point and elsewhere in the GL, any writes to
or reads from the buffer generate undefined values. Examples of such bindings
include ReadPixels to a pixel buffer object binding point and client access to a
buffer mapped with MapBufferRange."

From what I read here, it sounds like to me that even if for transform feedback objects that are not currently bound / active, their buffer bindings may still cause undefined behavior.

Just want to bring this up because I feel the intention is to only validate the buffer bindings for the currently bound / active transform feedback object.

**Comment by greggman** [comment]
That sounds like a poorly worded spec. If it was true that having a buffer on an unused TF was a problem it would make the entire concept of transform feedback objects pointless. The whole point of them is like VertexArrayObjects. You set them up with all in outputs at init time and then in one call you can setup all the outputs just before drawing. Since the point of transform feedback is to generate data that will then be used as inputs to attributes it makes zero sense you'd have to unbind them from every unused transform feedback object before you could use them in an attribute. If that was the case there would be no reason to setup transform feedback objects ever. You'd always use the default because you'd always have to bind and unbind all the buffers.

I'd suggest asking on the OpenGL ES mailing list for clarification but I see how the wording of the spec makes it sound like that's a possibility.

I don't understand though how ReadPixels has anything to do with transform feedback even if there was an active TF with the same buffer attached. ReadPixels is a sync-ish function. It happens after the draw not during the draw so there should be no conflict there. It would be nice to know why those warnings exist and what they really mean.

**Comment by zhenyao** [comment]
@shannonwoods Any input?

**Comment by shannonwoods** [comment]
The language can be traced back to this Khronos issue (requires Khronos access): https://cvs.khronos.org/bugzilla/show_bug.cgi?id=3004

It looks like the discussion there included explicit language that specified undefined values if buffer objects were bound to TRANSFORM_FEEDBACK_BUFFER and any other binding point, for both reads and writes. (See comment 10, if you have access.) It definitely reads as though the restriction on binding is purposeful.

In a previous discussion, @jdashg noted that the ES spec itself says "Buffers _should not be_ bound or in use for both transform feedback and other purposes..." rather than _may not be_. The original language in the ARB WG bug is more restrictive, so I'm not sure that "should not be" is meant to be intentionally permissive.

**Comment by greggman** [comment]
Linking to a private conversions is not very helpful for a supposedly public API discussion. Can you summarise the issues? The paragraph still does not make any sense whatsoever or else I'm missing something given that execution is sequential. Maybe they mean between the time transform feedback is enabled and disabled?

I'm curious what the actual restrictions are supposed to be. Given that transform feedback is not random access it seems like having a the same buffer as both an input and an output is specifically supported. Just after this completely unhelpful paragraph

> Buffers should not be bound or in use for both transform feedback and other
> purposes in the GL. Specifically, if a buffer object is simultaneously bound to a
> transform feedback buffer binding point and elsewhere in the GL, any writes to
> or reads from the buffer generate undefined values. Examples of such bindings
> include ReadPixels to a pixel buffer object binding point and client access to a
> buffer mapped with MapBufferRange

Is this one

> However, if a buffer object is written and read sequentially by transform feedback
> and other mechanisms, it is the responsibility of the GL to ensure that data
> are accessed consistently, even if the implementation performs the operations in a
> pipelined manner. For example, MapBufferRange may need to block pending the
> completion of a previous transform feedback operation.

That description "*a buffer object is written and read sequentially by transform feedback and other mechanisms*" to me sounds exactly like reading from an attribute and writing to an output (transform feedback).  That fact that it worked on my MBP because of a bug in chrome is what made me think (oh, this actually works, writing to the same buffer I'm reading from). Then I saw the paragraph above which seemed to confirm that it's supposed to work. (or else it too is a poorly worded paragraph)

It still seems like all of this should be brought up on the OpenGL ES list. The first paragraph needs to be more specific otherwise, like @zhenyao says it implies that all buffers on all transform feedback objects and all buffers on all vertex array object attributes, even ones that are not currently bound, need to be unbound from their respective transform feedback objects and vertex array objects. 

The second one makes it sound like reading from and writing to the same buffer is explicitly supported.

**Comment by shannonwoods** [comment]
Sorry. The question was about the intention of the spec, and the language originates in a Khronos-private forum, as most ES & GL language does, so I pointed to it and summarized the language origins.

My understanding is that the situation they were trying to address was that implementations might need to transition or copy the buffer to a different state/memory store in order to allow it to be used for transform feedback, and attempting to read from or write to it while it was in that state would not do what the application intended. They're not clear on whether such a migration can be reasonably expected to happen at bind time rather than at first XFB begin call.

The originally proposed language refers to buffers being "in use for transform feedback" rather than "bound to a transform feedback binding point"-- but later in the discussion, it's proposed that they be more specific about what "in use" means, at which point the language changed to "bound to a transform feedback binding point," which is what leads me to suspect that-- at least when this feature went from NV_transform_feedback & EXT_transform_feedback to a part of the core spec-- the restriction on reading/writing via some other mechanism while bound to TRANSFORM_FEEDBACK_BUFFER was intentional. But they didn't elaborate why on the bug.

**That said**, the GLES 3.1 CTS has at least one test where a simultaneous binding of GL_TRANSFORM_FEEDBACK_BUFFER and another binding point is expected to work (hey, open source!): https://github.com/KhronosGroup/VK-GL-CTS/blob/master/external/openglcts/modules/gles31/es31cDrawIndirectTests.cpp#L5031
I'm not intimately familiar with the rules around GL_DRAW_INDIRECT_BUFFER, but I can't quickly find any language in the ES 3.1 spec that would exempt it from the rules applying to other binding points WRT XFB.

I think it's worth asking the ES WG to clarify the intent and the language of the spec.

**Comment by shannonwoods** [comment]
I filed a bug with the ES WG asking for clarification.

**Comment by msc-** [comment]
This conversation is giving me a very strong sense of déja vu. Unfortuately I have failed to find the previous conversation. I will make a few points.

The OpenGL ES spec talks about undefined behavior not errors so errors and where to raise them are entirely the choice of WebGL. Clearly undefined behavior during reads and writes can only happen when, er, reading & writing so there it is not necessary to flag errors during bind operations.

If you are going to raise errors, problematic conditions must be checked not just during draw operations but also readPixels, copyPixels, uploads to PBOs and probably a few others I’m not recalling right now.
> Buffers should not be bound or in use for both transform feedback and other
> purposes in the GL. Specifically, if a buffer object is simultaneously bound to a
> transform feedback buffer binding point and elsewhere in the GL, any writes to
> or reads from the buffer generate undefined values. Examples of such bindings
> include ReadPixels to a pixel buffer object binding point and client access to a
> buffer mapped with MapBufferRange
> 

This seems clear enough to me. The basis, as Shannon explained, is the different memory types the GPU may need to use for these different purposes which together with the massively parallel machine mean no guarantees can be made as to whether the data seen in any one of the uses is the same as was written in another.

I agree with Gregg that a buffer bound to an unbound xfb object should not be considered bound for transform feedback. In my own native xfb application I leave the 2 ping-pong buffers permanently bound to their xfb objects and when ping-ponging only unbind the relevant xfb object.

> However, if a buffer object is written and read sequentially by transform feedback
> and other mechanisms, it is the responsibility of the GL to ensure that data
> are accessed consistently, even if the implementation performs the operations in a
> pipelined manner. For example, MapBufferRange may need to block pending the
> completion of a previous transform feedback operation.

I think sequentially here refers to unbinding a buffer object from xfb after an xfb capture then binding it somewhere else and reading it. The GL has to ensure the necessary barriers are in place to ensure what has come to be referred to as coherent access.

Regards

    -Mark

**Comment by greggman** [comment]
This issue is still not resolved and Firefox and Chrome have different behavior.

I still believe checking at bind time is against the spirit of OpenGL. It's very clear that checking at bind time will break ported content vs checking at draw time. Regardless though the behavior needs to be the same across browsers.

**Comment by zhenyao** [comment]
@kenrussell has been working on it. I lost track of the progress, maybe Ken can give an update.

**Comment by shannonwoods** [comment]
As far as the ES spec issue goes, it's still under discussion within the WG. They're unlikely to make any of the undefined behavior defined without verifying among all vendors that it's actually supportable.

**Comment by kenrussell** [comment]
I'm sorry for the lack of progress on this issue. A lot of other high-priority issues have come up. The resolution of the working group is that the transform feedback-related checks upon bind will be eliminated, and instead checks at the API entry points like tex{Sub}Image{2|3}D will be done. The conformance tests also need to be updated. I'll get back to this work shortly.

**Comment by kenrussell** [comment]
Just today there was some positive response from ARM about the direction that the only transform feedback object with which there should be conflicts is the currently bound one, not any one ever allocated in the context.

**Comment by greggman** [comment]
This is still unresolved. Firefox and Chrome still behave differently in the jsfiddle linked above

**Comment by kenrussell** [comment]
Acknowledged. Sorry for not getting to this yet but it's a large change and higher priority bugs keep coming in. I'll try to fix it within a week.
