### ISSUE TITLE
Clarify compressed texture size restrictions

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#2745]
In https://github.com/kripken/emscripten/pull/7557#issuecomment-442024094 a difference in behavior was seen between Chrome and Firefox in the handling of the size of the buffer passed in. Firefox required the buffer to be exactly the correct size, while Chrome allowed the buffer to be bigger. This behavior should be tested by the conformance suite.

**Comment by kenrussell** [comment]
CC @jdashg in particular.

**Comment by mosra** [comment]
(I'm the author of the referenced comment.) 

When I was going through Firefox sources to understand the source of the error, I spotted that it's allowing a PBO offset, but then requring the rest of the buffer to have exact size ([relevant part here](https://dxr.mozilla.org/mozilla-central/rev/4e56a2f51ad739ca52046723448f3129a58f1666/dom/canvas/WebGLTextureUpload.cpp#207-218)). Maybe I'm missing something, but I can imagine the offset being used to have more than one image stored in a single buffer, each at a different offset. In that case only the upload of the last image would succeed because for the others the remaining size would be larger. This feels a bit inconsistent to me, I would expect that either:

- no PBO offset is allowed at all, requiring each buffer to have exactly one image (then the exact size requirement makes sense)
- PBO offset is allowed and size requirement is lifted to "at least given size" instead of "exactly the size", allowing multiple images being uploaded from a single PBO

**Comment by jdashg** [comment]
Ah, yeah that's definitely the wrong way for us to handle PBOs.

**Comment by kenrussell** [comment]
Thanks @mosra for clarifying and @jdashg for your thought.

@mosra I wonder whether you might be able to find the time to modify some of the compressed texture conformance tests like:
https://github.com/KhronosGroup/WebGL/blob/master/sdk/tests/conformance/extensions/webgl-compressed-texture-s3tc.html

and add an optional code path (to be run when contextVersion >= 2) which uploads the data to a buffer object, and from there to a compressed texture? Similar to the current code which optionally uses texStorage2D.

**Comment by mosra** [comment]
@kenrussell almost four months later, but I was *finally* able to the time to submit a test case for this :) See #2831, let me know if there are any issues with it.

**Comment by kenrussell** [comment]
Fixed by #2831 . Thanks @mosra for this contribution.
