### ISSUE TITLE
Add conformance tests to cover DOM uploads update (#2805)

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/WebGL#2814]
As requested by @kenrussell in https://github.com/KhronosGroup/WebGL/pull/2805#issuecomment-468061152.

Current tests (`sdk/tests/js/tests/tex-image-and-sub-image-2d-with-image.js`) use the same `red-green.png` image (that contains RGB8 data) to test all WebGL internal formats. To cover updated behavior, we need to have two more source images and a new set of expected values.

Uploads from `HTMLCanvasElement`, `HTMLVideoElement`, `ImageBitmap`, and `ImageData`, are unaffected by the spec change, because these sources always have at least 3 channels, right? Is it OK to assume that SVG images are never internally rasterized to L or LA, so they are unaffected as well?

/cc @jdashg

**Comment by jdashg** [comment]
While we're in there, I guess we should add four-channel RGBA image sources, too.

We can leave SVG alone.

**Comment by kenrussell** [comment]
There are more tests in the conformance repository which verify things like premultiplication of the alpha channel, and handling of the alpha channel separately. See at least sdk/tests/conformance/textures/misc/gl-teximage.html which uses different image resources.

I don't know whether we need to expand the core tests in textures/image/ in order to cover the new cases. Those tests are fairly expensive especially because of the large number of new internal formats being tested in the WebGL 2.0 variants in conformance2/textures/image/ .

Maybe the better approach is to add targeted tests in conformance[2]/textures/misc.
