### ISSUE TITLE
Whether consider ColorMask settings when detect mismatch of frag output and drawbuffer attachments

### ISSUE THREAD

**Issue by shrekshao** [KhronosGroup/WebGL#2880]
Follow up of https://github.com/KhronosGroup/WebGL/pull/2780
There's a recent discussion brought up by the skia team. Seems that we didn't mention whether it's still an invalid operation when glColorMask is set to all false here.
I didn't find any discussion or sentences from spec declaring this active drawbufer and frag output mismatch is regardless of mask settings yet. (Let me know if there is).
However I do remember we do have tests indicating feedback loop detection is regardless of mask settings.
So intuitively I'd say we should not take into account the mask setting here as well. Maybe there's more solid reasons for not considering mask setting in driver level as it's a fine buffer control and there are evidence showing that even if it's set to fully false there's still samples combined (OpenGL ES 3 spec section 4.2.2.1)
If we all agree on this I can update the tests with some glColorMask call following the pattern of those in feedback loop tests, showing they should not affect anything here.

Jeff's comment
> I would like us to not have to check ColorMask, but I could go either way on it. Clearly if ColorMask is disabled, no color outputs will be written.

**Comment by kainino0x** [comment]
As I mentioned on the Chromium CL, I'm weakly in support of ignoring the ColorMask here too.

**Comment by null77** [comment]
I'm pretty strong in favor of ignoring color mask. There's no mention of color mask in any of the spec definitions of a feedback loop.

**Comment by kainino0x** [comment]
Comment from Brian Osman:

> Counter-points:
> 1) There's no actual feedback loop here. The GL specs make it pretty clear that bound buffers with no corresponding output from the FP get an undefined value. Even if the output is undefined, masking still prevents writes of that value (it even seems pretty clear that it's intended as a more fine-grained version of DrawBuffer(s) from where it shows up in the spec and continues the verbiage from the previous section).
> 2) No driver or GL implementation has ever complained about this before.
> 3) DrawBuffer(s) isn't in ES2 - ColorMask is literally the only way to control color writes in an ES2 context.

**Comment by null77** [comment]
There is technically a feedback loop according to the spec. I do agree in practice it's unlikely a driver would write to an output in this case.

My question to Brian Osman would be what this buys them in return for making validation slower and more complex? I would want to know if there's a solution they could use on their side.

**Comment by kenrussell** [comment]
Brian makes good points that the only practical way in ES 2.0 to avoid this rendering feedback loop is to use ColorMask to avoid potentially undefined writes, and that no OpenGL driver has complained about this before.

WebGL aims to eliminate as much undefined behavior as possible, but it has also followed the behavior implicitly defined by drivers. In some cases WebGL has motivated changes to the OpenGL spec defining the widely implemented behavior; @jdarpinian 's work on transform feedback and behavior fo the generic transform feedback buffer binding point is one recent example.

I think we should change the validation rules that were just imposed to be more compatible with this existing code. Specifically, I think we should take ColorMask into account and allow the draws if color writes to all channels are disabled.

Note Chrome bug http://crbug.com/763695 about depth/stencil feedback loops. There the OpenGL ES working group resolved that disabling depth writes wasn't sufficient to resolve rendering feedback loops, but the color buffer can be special-cased since it is clear that all platforms handle this case correctly.

Thoughts?

**Comment by null77** [comment]
I'm still curious as to what Brian's situation is that he can't work around. Or that it's difficult to work around. Why would he be using shaders with no outputs and binding a framebuffer with outputs?

**Comment by brianosman** [comment]
Our specific use-case that triggered this bug was stencil-only draws. The FBO had a color attachment, but we weren't outputting any color values because we were just filling stencil. I'd be happy to see the WebGL spec go either way (and we can abide by whatever rules are in place), but the other issue is that Chrome's command buffer is now enforcing this validation rule - even for contexts that are not WebGL. We started encountering this while simply using command buffer as a boring ES2 context.

To make things worse, in un-extended ES2, there is no glDrawBuffers. So command buffer on top of un-extended ES2 literally offers no way to get around this validation error.

**Comment by null77** [comment]
That's a serious problem if Chromium is applying WebGL validation rules to non-WebGL contexts. Could you file an issue for that in the Chromium issue tracker at http://crbug.com/new ?

When you say there's no way to get around this validation error, is this a Surface Framebuffer? If so the you could work around this error by writing to gl_FragColor in your shader and also disabling color writes with ColorMask. But that is a valid point of  inconvenience.

**Comment by brianosman** [comment]
Filed a bug to restrict the validation logic that was added. https://bugs.chromium.org/p/chromium/issues/detail?id=959955
