### ISSUE TITLE
multi_draw_* and *_base_vertex_base_instance extensions: change prefix from WEBGL_ to ANGLE_

### ISSUE THREAD

**Issue by shrekshao** [KhronosGroup/WebGL#2963]
When we implement these extensions in browsers, we find it a bit confusing to prefix these extensions with `WEBGL_` while they share the same function signatures with that in ANGLE.

We might want to replace them with `ANGLE_`

**Comment by kenrussell** [comment]
A little more background: ANGLE's extensions which implement these WebGL extensions are defined here:
https://chromium.googlesource.com/angle/angle/+/refs/heads/master/extensions/

So perhaps it makes sense to just expose those extension names, rather than renaming them to use the WEBGL_ prefix, since they're being exposed verbatim to WebGL.
