### ISSUE TITLE
using texImage2D in WebGL2 with different width and height than image

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#3068]
Looking at the spec I see this appears not to be supposed to work but I'm wondering why the restriction.

My understanding of the spec is when you pass a `TexImageSource` (an HTMLImageElement, HTMLCanvasElement, ...) 

> The source image data is conceptually first converted to the data type and format specified by the format and type arguments

So the flow is basically

1.  hunkOfData = convertTexSourceToFormatType(sourceElement, format, type);
2.  glTexImage2D(............., format, type, hunkOfData);

So, given that taking a 256x1 image and uploading it as a 16x16 image should be possible.

```
// WebGL2
gl.texImage2D(
    gl.TEXTURE_2D,
    0,  // level
    gl.RGBA8,
    16,  // width
    16,  // height
    0,  // border
    gl.RGBA,
    gl.UNSIGNED_BYTE,
    some256x1Image);
```

which translates to

```
dataFor256RGBA8Pixels = convertTexSourceToFormatType(some256x1Image, gl.RGBA, gl.UNSIGNED_BYTE);
glTexImage2D(
    gl.TEXTURE_2D,
    0,  // level
    gl.RGBA8,
    16,  // width
    16,  // height
    0,  // border
    gl.RGBA,
    gl.UNSIGNED_BYTE,
    dataFor256RGBA8Pixels);
```

Which is perfectly valid OpenGL but not valid WebGL2.

It seems to me given the spec says

> The source image data is conceptually first converted to the data type and format specified by the format and type arguments

That both the dev and the browser know exactly how how many bytes and the format that will be created by that process so after which any valid width, height, and unpack parameters that would fit that data should be valid.

Is there some reason the restrictions are tighter?

Note: fit the data to me = not out of bounds. It does not mean "uses all the data" so for example

```
// extract a 137x1 texture from a 256x1 image
gl.texImage2D(
    gl.TEXTURE_2D,
    0,  // level
    gl.RGBA8,
    137,  // width
    1,  // height
    0,  // border
    gl.RGBA,
    gl.UNSIGNED_BYTE,
    some256x1Image);
```

should work (and it does)

but so should

```
// extract a 128x2 texture from a 256x1 image
gl.texImage2D(
    gl.TEXTURE_2D,
    0,  // level
    gl.RGBA8,
    128,  // width
    2,  // height
    0,  // border
    gl.RGBA,
    gl.UNSIGNED_BYTE,
    some256x1Image);
```

and that fails. Should it?

**Comment by kenrussell** [comment]
This behavior is by design. HTML sources don't always behave like a stream of bytes. When uploading HTML canvases to WebGL textures, for example, the fastest paths are implemented with copies between GPU textures. Reinterpreting a 256x1 texture as a 128x2 texture is not possible in this scenario, and would involve slow CPU readbacks (or at least readbacks into pixel buffer objects and re-uploads from them), leading to hard-to-explain performance cliffs in application code.

Certain special cases have already been integrated into the WebGL 2.0 spec - like the ability to select a sub-rectangle of an HTML source like an image or canvas. These are well tested and work with options like the FLIP_Y pixel unpack parameter.

At this stage in WebGL's lifecycle I think it's better to keep the WebGL spec in this area as is. Please reopen if you feel strongly that changes are needed.
