### ISSUE TITLE
Investigate bindUniformLocation extension

### ISSUE THREAD

**Issue by kenrussell** [KhronosGroup/WebGL#3133]
In a discussion with @juj from Unity, it was pointed out that in Unity's HTML5 / WebGL export path, necessary introspection on shaders causes many round-trips to be made through the WebGL API to fetch programs' uniform locations. These queries consume a considerable amount of startup time, and also cause slowdowns at run time if programs need to be loaded on the fly.

On Unity's other platforms, like desktop OpenGL or OpenGL ES >= 3.1, the engine uses explicit uniform locations in its shaders to avoid these round-trips. However, WebGL's uniform locations were deliberately designed as opaque objects rather than ints as in the OpenGL ES API in order to avoid portability hazards with applications making incorrect assumptions about their contiguity, or performing incorrect arithmetic on them.

One potential middle ground could be to add a bindUniformLocation extension to WebGL. Applications could choose numbers that conform to a particular set of constraints, and the WebGL implementation could quickly validate against those and more rapidly produce WebGLUniformLocation instances than making round-trip calls through the API.

Such an extension already exists in Chromium's remoted OpenGL ES implementation:
https://chromium.googlesource.com/angle/angle/+/HEAD/extensions/CHROMIUM_bind_uniform_location.txt

Perhaps it could be generalized and exposed to WebGL.

Note though that other work to make KHR_parallel_shader_compile more fully asynchronous - for example in http://crbug.com/1103499 - might obviate the need for this extension.

**Comment by jdashg** [comment]
bindUniformLocation would totally work for this, but so would a webgl.createUniformLocation(prog, name) I think. createUniformLocation would preserve our opaqueness here, while being async "push-only" from client/content to host/gpu-process.

**Comment by juj** [comment]
Indeed there's two issues with the opaque [WebGLUniformLocation](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.10) interface object:

1. Each shader program needs to produce a mapping int -> WebGLUniformLocation. In Emscripten that is managed in 

https://github.com/emscripten-core/emscripten/blob/77d7739b50a765c8208c5e6105ef58b6e21ed163/src/library_webgl.js#L1116-L1123

This mapping can take ~10-20msecs of time when populating shaders with large amounts of uniforms, or uniform arrays. Also our current code is likely wrong for very complex UBOs, arrays-of-arrays, structs-of-structs, arrays-of-structs-of-arrays, or struct-of-arrays-of-structs configuration (modulo what WebGL permits), but nobody has complained, so they are probably not being used in the wild.

2. On desktop GL and GLES we rely heavily on specifying layouts in shaders using `layout(location = x)`, e.g.
```glsl
#version 300 es
precision highp float;
precision highp int;
#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
#if UNITY_SUPPORTS_UNIFORM_LOCATION
#define UNITY_LOCATION(x) layout(location = x)
#define UNITY_BINDING(x) layout(binding = x, std140)
#else
#define UNITY_LOCATION(x)
#define UNITY_BINDING(x) layout(std140)
#endif
UNITY_LOCATION(0) uniform mediump sampler2D _MainTex;
in mediump vec4 vs_COLOR0;
in highp vec2 vs_TEXCOORD0;
layout(location = 0) out mediump vec4 SV_Target0;
vec4 u_xlat0;
mediump vec4 u_xlat16_0;
void main()
{
    u_xlat0 = texture(_MainTex, vs_TEXCOORD0.xy);
    u_xlat16_0 = u_xlat0 * vs_COLOR0;
    SV_Target0.xyz = u_xlat16_0.www * u_xlat16_0.xyz;
    SV_Target0.w = u_xlat16_0.w;
    return;
}
```

For the first problem, adding a new API parallel to WebGL `.getUniformLocation()` that would return direct integers rather than `WebGLUniformLocation` objects would solve the issue.

That would then enable to resolve the second problem by adding support for https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_shading_language_420pack.txt (for UBO `layout(binding=x)` rule) and https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_explicit_uniform_location.txt to WebGL.

It seems that a `.bindUniformLocation()` would not solve either of the above issues, as for point 1) it would then require one to loop over all uniforms (and complex constructs, e.g. structs-of-arrays-of-structs) anyway to bind them all in place, and for 2) it would be from the wrong direction, i.e. the desirable bit would be to have the `layout(location=x)` specifiers in shaders.

We are currently experimenting with a hacky preprocessing-based implementation of https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_shading_language_420pack.txt and https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_explicit_uniform_location.txt to Emscripten layer by preprocessing the shader code in Emscripten, and recognizing+filtering out the `layout()` specifiers that are found, and performing `populateUniformTable` logic based on the extracted information. It will be a bit crude and brittle, but will unblock us to experiment and prototype with the functionality that it would give.

**Comment by katherinehecht** [comment]
Hi @juj!
I also have the issue documented above and am wondering if any solution arose from your experimentation. My project uses Unity version 2019.4.11.f1. Thanks and please let me know.

**Comment by juj** [comment]
We are working on a solution, but unfortunately one does not exist quite yet. (implementing compressed audio support to Unity took priority away from the allocated engineer time to prototype a fix for this)

**Comment by kenrussell** [comment]
@juj has proposed a fantastic emulation layer for this in Emscripten in https://github.com/emscripten-core/emscripten/pull/13732 . This is a good solution because it doesn't require all browsers to be updated with an additional WebGL extension. Closing this issue.
