### ISSUE TITLE
In GLES, attribute names can be the same as fragment-only uniform names

### ISSUE THREAD

**Issue by null77** [KhronosGroup/WebGL#3201]
See this ANGLE bug: http://anglebug.com/5497

In the GLSL ES Spec 3.00.3, section 4.3.5:

```
  If a uniform variable name is declared in one stage (e.g., a vertex shader)
  but not in another (e.g., a fragment shader), then that name is still
  available in the other stage for a different use
```

WebGL explicitly prohibits this behaviour:

https://github.com/KhronosGroup/WebGL/blob/master/sdk/tests/conformance/glsl/misc/shaders-with-name-conflicts.html#L60

```
Note: This was brought up on the OpenGL ES working group and confirmed
that the spec required these conflicts to fail to link.

Though most drivers allow this to work, some drivers to do no therefore
WebGL implementation must enforce this restriction to provide consistent
behavior.
```

Is there any link to this conversation? Seems like that is inconsistent with the language in the spec.

**Comment by kenrussell** [comment]
The test was written against the GLSL ES 1.0.17 specification, which as described in the test case was ambiguous in this area, and drivers had differing behavior. This required forbidding these kinds of conflicts.

I dug up the discussion from the OpenGL ES mailing list (Khronos members only):

https://members.khronos.org/wg/OpenGL_ES/mail/thread/113379
https://members.khronos.org/wg/OpenGL_ES/mail/thread/113384
https://members.khronos.org/wg/OpenGL_ES/mail/thread/113388
https://members.khronos.org/wg/OpenGL_ES/mail/thread/113392

It would be fine to remove this restriction for ESSL 3.00 shaders in ANGLE, since the spec and presumably conformance tests were clarified in this area. Please leave the restriction in place for ESSL 1.00 shaders.

**Comment by null77** [comment]
Ken, I suspect the WG gave Gregg incorrect information back in 2013. They don't usually change this kind of linking behaviour based on shader spec. I'll bring it up at the next WG meeting. It seems pretty weird and inconsistent to make this depend on shader version.

**Comment by null77** [comment]
Filed https://gitlab.khronos.org/GLSL/GLSL/-/issues/29 (Khronos members-only link)

**Comment by kenrussell** [comment]
Per resolution of the above Khronos-internal bug:

<pre>
[On an OpenGL ES working group conference] call today, there was consensus that attribute names should be allowed to alias fragment uniforms in GLSL ES 1.00. Historically this may be related to the original GPU hardware having separate fragment and vertex processing. Since there are lots of prior cases where spec clarifications are not back-ported to older specs there's no need to make an amendment to the 1.00 spec.
</pre>

Thanks @null77 for confirming that this aliasing is expected to work on all current mobile hardware. We'll update the WebGL conformance tests to require that this works, rather than that this doesn't work.
