### ISSUE TITLE
Case gl-bindAttribLocation-aliasing.html timeout in python script

### ISSUE THREAD

**Issue by weijiang1994** [KhronosGroup/WebGL#3332]
Log info

[![1630772955175.png](https://bu.dusays.com/2021/09/05/6cc35424dc743.png)](https://bu.dusays.com/2021/09/05/6cc35424dc743.png)

**Comment by kenrussell** [comment]
Unfortunately I don't think any of the browser implementers are using the webdriver harness in the WebGL conformance repository; on our internal CI systems we're using more browser-specific harnesses.

@gyagp any chance you could look into this report?

**Comment by gyagp** [comment]
I don't have Linux machine at hand today, so I tried Windows and it worked well. I will be on leave tomorrow, and I can give a try on Linux next week. 
It seems the issue was caused by timeout. Can you directly open the browser and run WebGL CTS?

**Comment by weijiang1994** [comment]
@gyagp @kenrussell Thanks for your reply. This problem was caused by timeout,  I tried to open the browser to run WebGL CTS, but the run button was disabled. This test suite runs well on Ubuntu2004, but the above problems will appear in the Deepin OS.

**Comment by gyagp** [comment]
I tried Ubuntu 21.04, and everything worked fine at my side. 
![Screenshot from 2021-09-13 11-11-31](https://user-images.githubusercontent.com/218432/133020323-13e6e099-fc35-4d56-b3d1-0856cee27896.png)

@weijiang1994, I think you need to figure out why WebGL CTS couldn't run at all at your side. Will https://get.webgl.org/ work at your side? How about other browsers, like Firefox?
If the issue is Chrome specific, you may simply file bug via crbug.com/new and paste content from chrome://gpu there.  

BTW, @kenrussell, I will submit a PR to fix several compatibility issues that are not related to this one

**Comment by weijiang1994** [comment]
> I tried Ubuntu 21.04, and everything worked fine at my side.
> ![Screenshot from 2021-09-13 11-11-31](https://user-images.githubusercontent.com/218432/133020323-13e6e099-fc35-4d56-b3d1-0856cee27896.png)
> 
> @weijiang1994, I think you need to figure out why WebGL CTS couldn't run at all at your side. Will https://get.webgl.org/ work at your side? How about other browsers, like Firefox?
> If the issue is Chrome specific, you may simply file bug via crbug.com/new and paste content from chrome://gpu there.
> 
> BTW, @kenrussell, I will submit a PR to fix several compatibility issues that are not related to this one

OK... Thanks
