### ISSUE TITLE
WebGLObject is specified in IDL but none of the implementations implement it

### ISSUE THREAD

**Issue by kkinnunen-apple** [KhronosGroup/WebGL#3542]
WebGLObject is specified in IDL but none of the implementations implement it

Maybe remove from IDL? It appears to be a specification vehicle, similar to *invalidated* flag.

Comes up in https://github.com/web-platform-tests/interop/issues/363

**Comment by kenrussell** [comment]
It turned out that this was straightforwardly implementable in Chromium at least - [CL implementing it](https://chromium-review.googlesource.com/c/chromium/src/+/5466430), [Bug](https://issues.chromium.org/issues/326353887), [ChromeStatus entry](https://chromestatus.com/feature/5119115615535104). There's agreement among vendors to not remove this interface because it's desired to add to it, so closing this issue.
