### ISSUE TITLE
No new extensions (mostly)

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/WebGL#3559]
This isn't up to me but my feeling is WebGL is done and browser teams are moving on to WebGPU.

Every feature added to WebGL is time all browser teams (at a minimum, Chromium, Firefox, WebKit) need to spend adding and maintaining these extensions. If all browsers don't add them they then are not that useful for devs. They all require maintenance forever, for example when some driver claims to support them but exhibits bugs or different behavior. They require tests which take time and resources on browser teams' CI infrastructure, etc.

The same teams that implement and maintain WebGL are usually the teams that maintain and implement WebGPU and those teams have limited time and resources.

So, if it was up to me, I'd mostly declare WebGL done, no new extensions. To be clear, I'm speaking for myself. I am not speaking for the team I'm on nor my employer. It's just my personal opinion.

Maybe people just want to see these approved as specs that could theoretically be implemented but I'd guess, none of the browser teams want to prioritize implementing and maintaining these to their already large list of things they need to implement and maintain.

The only reason I say "mostly", is I suspect there is desire by browser teams to keep WebGL working with other possible new web features like HDR canvas. I think they'd prefer to do that without new extensions but if it was found to be impossible without a new extension then I'm guessing extensions to cover that would be added. As it is though, I can't think of any off the top of my head that would need to be added for HDR canvas. Of course I can't predict the future and what forward features might come up. GPU features though, (compute, ML, ray tracing, mesh shaders, etc....) will likely be targeted at WebGPU, not WebGL.

**Comment by kenrussell** [comment]
Thank you Gregg for your input. Your point is well taken about focusing effort on WebGPU rather than WebGL at the present time. At the same time, the WebGL working group has discussed Alexey's extension proposals at length during meetings, and has decided that as long as many or most of these can be implemented across browsers with minimal effort, doing so can enhance the WebGL ecosystem and provide a testbed for exposing similar functionality in WebGPU. I'm going to close this issue for this reason.
