### ISSUE TITLE
There is no way to initialize a compressed 2D or 3D texture with uninitialized contents

### ISSUE THREAD

**Issue by juj** [KhronosGroup/WebGL#3686]
According to GLES 3.0 spec, when calling glCompressedTexImage2D or glCompressedTexImage3D, if one passes a null data pointer, then a texture with uninitialized contents should be allocated in GPU memory:

![image](https://github.com/user-attachments/assets/36e2b58d-2f3f-4f24-84c3-c7d899d9572c)

This behavior is the same as with glTexImage2D and glTexImage3D. E.g. to create a 2D texture in WebGL with uninitialized memory contents, one can call

`GL.texImage2D(target, level, internalFormat, width, height, border, format, type, null);`

However, it looks like creating an uninitialized compressed 2D texture is not possible in WebGL. Attempting to run

```html
<!DOCTYPE html><html><body><script>
var gl = document.createElement("canvas").getContext('webgl');
gl.bindTexture(gl.TEXTURE_2D, gl.createTexture());
var dxt1 = gl.getExtension('WEBGL_compressed_texture_s3tc').COMPRESSED_RGB_S3TC_DXT1_EXT;
gl.compressedTexImage2D(gl.TEXTURE_2D, 0, dxt1, 4, 4, 0, null);
</script></body></html>
```

generates errors in both Chrome and Firefox:

![image](https://github.com/user-attachments/assets/c609616b-814e-4c69-ab99-c4e02b99a438)

![image](https://github.com/user-attachments/assets/8fa08798-b349-4ab2-b289-c08d6359b7eb)

Reading the spec, in case of `texImage2D`, the parameter `pixels` is marked with a `?` to be optional:

![image](https://github.com/user-attachments/assets/00e187fe-6db1-47ea-a890-63f3aab1530f)

However for `compressedTexImage2D`, this optionality is not present:

![image](https://github.com/user-attachments/assets/038a7723-56a1-4c87-bc28-7b864f6de1a8)

Reading section "Differences Between WebGL and OpenGL ES 2.0" on compressed textures, there is no mention of an intentional discrepancy between passing null to texImage2D() vs compressedTextImage2D():

![image](https://github.com/user-attachments/assets/91fda103-2767-4c8b-8bd1-d6c87e10bbc4)

suggesting that this may be an unintentional oversight? Or if there is a rationale, it might be good to note in the above section?

This was originally found in https://github.com/emscripten-core/emscripten/issues/19300.

**Comment by kenrussell** [comment]
There is a supported method in WebGL 2.0 to allocate an empty compressed texture: use `texStorage2D` or `texStorage3D`. WebGL 2.0 (and OpenGL ES 3.0) added the ability to specify textures' internal formats; but only the `texStorage` entry points were updated to support compressed textures. See this comment in Chromium's (older) WebGL implementation path:

https://source.chromium.org/chromium/chromium/src/+/main:gpu/command_buffer/service/gles2_cmd_decoder.cc;l=12378?q=GLES2DecoderImpl::ClearCompressedTextureLevel&ss=chromium

When WebGL 2.0 was underway I don't remember whether the working group noticed that `glCompressedTexImage2D` was changed in OpenGL ES 3.0 to allow NULL data. Either way it would have been difficult to support this in WebGL. Web IDL would not allow WebGL 2.0 to make the `ArrayBufferView` nullable while leaving it required in WebGL 1.0, in the `undefined compressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, [AllowShared] ArrayBufferView data);` entry point. The WG probably determined that it was better to leave this argument required in the WebGL API rather than making it nullable and introducing a new `INVALID_OPERATION` or `INVALID_VALUE` error in WebGL 1.0 after the fact.

Does this address the question? I do not think a change to WebGL's entry points should be made, but a spec clarification could be added if you think it's warranted.

**Comment by juj** [comment]
> `glCompressedTexImage2D` was changed in OpenGL ES 3.0 to allow NULL data.

I am not so sure that in GLES2 -> GLES3 the spec was changed to allow null data, but rather, it seems to me that the GLES2 spec accidentally omitted mentioning what should happen on a null pointer.

The only mention about what `data` should mean in GLES2 spec for glCompressedTexImage2D I can find is this part:

![image](https://github.com/user-attachments/assets/5d827fce-aaf8-409f-bdb7-e3a49c0445eb)

I think there may just have been a casual use of speech ambiguity. I could see the wording to as well been written as

"The _target_, _level_, _internalformat_, _width_, _height_, _border_ and _data_ parameters have the same meaning as in TexImage2D, except that _data_ points to compressed image data ..."

which would have implied that data can be null. But since `data` referred to compressed pixels instead of uncompressed pixels, they split out that one parameter to its own sentence, and then omitting declaring at all how `data` should be handled.

Reading through the whole part, it looks like the GLES2 spec does not state what would happen if null is passed to glCompressedTexImage2D at all, to positive or negative.

Anyhow, what was ambiguous/unspecified then is still unspecified now, so none of that really matters here.

I don't think it is worth the effort to consider changing spec or functional browser behavior, but probably good to address these kind of subtle gotchas in documentation in the spec.

E.g. maybe add in the differences between WebGL and OpenGL ES section about Compressed Textures a part

"In OpenGL ES 2.0 the specification omitted declaring whether it should be possible to create a compressed 2D texture with uninitialized data. In WebGL 1, this is explicitly disallowed.
In OpenGL ES 3.0 it is explicitly allowed to create a compressed 2D texture with uninitialized data by passing null to CompressedTexImage2D. In WebGL 2, this is however still explicitly disallowed. Users can call TexStorage2D to work around this functional difference."

or something along those lines.

Unfortunately Emscripten will not be able to transparently use TexStorage2D/3D as a workaround to allow users to specify uninitialized compressed 2D/3D textures. This is because there is a semantic difference between (Compressed)TexImage2D/3D and TexStorage2D/3D that TexStorage generates **immutable-format textures** (observable via glGetTexParameter of GL_TEXTURE_IMMUTABLE_FORMAT), so there is a functional difference and resulting semantical restrictions that follow.

Of course for any engine developers, migrating from (Compressed)TexImage2D/3D to TexStorage2D/3D in this manner may be possible.
